name: Build and Push Docker Image to ECR
on:
  push:
    paths:
      - Dockerfile
      - app.py

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker Image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.ECR_REPOSITORY_NAME }}:latest .

      - name: Tag Docker Image
        run: |
          ECR_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
          docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:latest $ECR_URI/${{ secrets.ECR_REPOSITORY_NAME:latest

      - name: Push Docker Image to ECR
        run: |
          ECR_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
          docker push $ECR_URI/${{ secrets.ECR_REPOSITORY_NAME }}:latest